// DarkAbsolut — CSS generation and injection.
//
// The inversion technique is a single page-level CSS filter that flips
// the whole document. Media and explicitly-tagged elements get a
// counter-filter so their colors survive correctly.

(function (DA) {
  "use strict";

  function buildInversionCss() {
    const ATTR = DA.ATTR;
    return `
html[${ATTR}="on"] {
  filter: invert(1) hue-rotate(180deg) !important;
}
/* Zero-specificity fallback bg: any site rule (e.g. html.dark { background })
   wins so effectiveBgColor() can read the real native bg and detect dark.
   A higher-specificity override on <html> would mask the site's real
   background and break dark-detection on sites where the dark color is set
   via html.dark{background:...} while <body> stays bg-white. */
:where(html[${ATTR}="on"]) {
  background-color: #ffffff;
}
/* NOTE: do NOT include <picture> here. <picture> is a wrapper around its
   child <img>; if both get the counter-filter the inversion is applied
   twice on the rendered image, which combined with the page-level filter
   on <html> compounds to an odd-numbered total invert and the photo
   ends up looking like a color negative on responsive-image sites
   (airbnb, instagram, modern news sites). The <img> rule alone covers
   it correctly. */
html[${ATTR}="on"] img,
html[${ATTR}="on"] video,
html[${ATTR}="on"] embed,
html[${ATTR}="on"] object,
html[${ATTR}="on"] canvas,
html[${ATTR}="on"] svg image,
html[${ATTR}="on"] [${DA.BG_IMAGE_ATTR}="1"],
html[${ATTR}="on"] [${DA.NATIVE_DARK_ATTR}="1"] {
  filter: invert(1) hue-rotate(180deg) !important;
}
/* Avoid double-inverting svg icons that use currentColor (treat as text) */
html[${ATTR}="on"] svg:not([${DA.BG_IMAGE_ATTR}="1"]):not(:has(image)) {
  filter: none !important;
}
/* ── Light islands on already-dark pages ─────────────────────────────────
   When the page is detected as already-dark we leave the root filter off
   so the site's dark theme is preserved. But dynamically-mounted light
   subtrees (e.g. Gmail message iframes, the "New message" compose dialog)
   need their own local inversion so their content is readable. Tagged by
   elements.js::tagLightIslands. Rules only fire when root is OFF to
   avoid double-inversion on light pages. */
html:not([${ATTR}="on"]) [${DA.NATIVE_LIGHT_ATTR}="1"] {
  filter: invert(1) hue-rotate(180deg) !important;
}
/* Re-invert media and bg-image descendants inside light islands so
   photos, icons and decorative imagery keep their real colors. */
html:not([${ATTR}="on"]) [${DA.NATIVE_LIGHT_ATTR}="1"] img,
html:not([${ATTR}="on"]) [${DA.NATIVE_LIGHT_ATTR}="1"] video,
html:not([${ATTR}="on"]) [${DA.NATIVE_LIGHT_ATTR}="1"] embed,
html:not([${ATTR}="on"]) [${DA.NATIVE_LIGHT_ATTR}="1"] object,
html:not([${ATTR}="on"]) [${DA.NATIVE_LIGHT_ATTR}="1"] canvas,
html:not([${ATTR}="on"]) [${DA.NATIVE_LIGHT_ATTR}="1"] svg image,
html:not([${ATTR}="on"]) [${DA.NATIVE_LIGHT_ATTR}="1"] [${DA.BG_IMAGE_ATTR}="1"] {
  filter: invert(1) hue-rotate(180deg) !important;
}
html:not([${ATTR}="on"]) [${DA.NATIVE_LIGHT_ATTR}="1"] svg:not([${DA.BG_IMAGE_ATTR}="1"]):not(:has(image)) {
  filter: none !important;
}
`;
  }

  function ensureStyle() {
    let style = document.getElementById(DA.STYLE_ID);
    const css = buildInversionCss();
    if (!style) {
      style = document.createElement("style");
      style.id = DA.STYLE_ID;
      style.textContent = css;
      (document.head || document.documentElement).appendChild(style);
    } else if (style.textContent !== css) {
      // Existing style was generated by an older version of the
      // extension (e.g. after an in-place upgrade). Replace it so the
      // current selectors / per-site flags actually take effect.
      style.textContent = css;
    }
    return style;
  }

  // Re-add our attribute / style node if a framework (e.g. React hydration,
  // next-themes) wiped them while we still believe inversion should be on.
  function ensureAttributeAndStyle() {
    if (document.documentElement.getAttribute(DA.ATTR) !== "on") {
      document.documentElement.setAttribute(DA.ATTR, "on");
    }
    if (!document.getElementById(DA.STYLE_ID)) {
      ensureStyle();
    }
  }

  // Toggle the per-site "don't invert images" flag on <html>. The CSS
  // selectors above key off this attribute so the change is purely
  // declarative — no per-element work needed.
  function setImageInversionDisabled(disabled) {
    const html = document.documentElement;
    if (!html) return;
    if (disabled) html.setAttribute(DA.NOIMG_ATTR, "1");
    else html.removeAttribute(DA.NOIMG_ATTR);
  }

  // ── Shadow DOM support ───────────────────────────────────────────────────
  // The page-level `filter: invert()` on <html> inverts everything it paints —
  // including content inside shadow roots. But the counter-invert rules above
  // live in the document's stylesheet and CSS does not cross shadow boundaries,
  // so media inside a shadow root (e.g. ad/sponsored web components) is inverted
  // once with no counter-invert → a colour-negative image. We fix this by
  // adopting an equivalent, shadow-scoped stylesheet into each shadow root.
  function buildShadowCss() {
    return `
img, video, embed, object, canvas, svg image,
[${DA.BG_IMAGE_ATTR}="1"], [${DA.NATIVE_DARK_ATTR}="1"] {
  filter: invert(1) hue-rotate(180deg) !important;
}
svg:not([${DA.BG_IMAGE_ATTR}="1"]):not(:has(image)) { filter: none !important; }
`;
  }

  let shadowSheet = null;
  function getShadowSheet() {
    if (shadowSheet) return shadowSheet;
    try {
      shadowSheet = new CSSStyleSheet();
      shadowSheet.replaceSync(buildShadowCss());
    } catch (_) {
      shadowSheet = null; // constructable stylesheets unsupported — caller falls back
    }
    return shadowSheet;
  }

  // Make a shadow root re-invert its media. Prefers adoptedStyleSheets; falls
  // back to appending a <style> node when constructable stylesheets are absent.
  function applyShadowStyle(root) {
    if (!root) return;
    const sheet = getShadowSheet();
    if (sheet && Array.isArray(root.adoptedStyleSheets)) {
      if (!root.adoptedStyleSheets.includes(sheet)) {
        try { root.adoptedStyleSheets = [...root.adoptedStyleSheets, sheet]; return; }
        catch (_) { /* fall through to <style> */ }
      } else { return; }
    }
    if (!root.getElementById || !root.getElementById(DA.STYLE_ID)) {
      try {
        const s = document.createElement("style");
        s.id = DA.STYLE_ID;
        s.textContent = buildShadowCss();
        root.appendChild(s);
      } catch (_) {}
    }
  }

  function removeShadowStyle(root) {
    if (!root) return;
    try {
      if (shadowSheet && Array.isArray(root.adoptedStyleSheets)) {
        root.adoptedStyleSheets = root.adoptedStyleSheets.filter(s => s !== shadowSheet);
      }
      const s = root.getElementById && root.getElementById(DA.STYLE_ID);
      if (s) s.remove();
    } catch (_) {}
  }

  DA.styles = {
    buildInversionCss,
    ensureStyle,
    ensureAttributeAndStyle,
    setImageInversionDisabled,
    applyShadowStyle,
    removeShadowStyle
  };
})(DA);
